config/routes.rb
Rails.application.routes.draw do
  resources :sentences, only: [:index, :show, :edit, :update]

  root 'sentences#index'
  match 'start', to: 'answers#start', via: 'get'
  match 'mark',  to: 'answers#mark',  via: 'post'
end

app/models/answer.rb
class Answer
  # include ActiveModel::Model

  # attr_accessor :questions
  # attr_accessor :sentence, :answer
  #
  # def initialize(attr = {})
  #   if !attr.empty?
  #   s = choice_sentence
  #   @id = s.id
  #   @japanese = s.japanese
  # end
  def self.choice_sentence
    id = rand(Sentence.count) + 1
    Sentence.find(id)
  end

  def self.mark(user_answer: '', correct_answer: '')
    user_answer == correct_answer
  end

end

app/models/count.rb
class Count < ActiveRecord::Base
  belongs_to :sentence
end

app/models/sentence.rb
class Sentence < ActiveRecord::Base
  has_one :count
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  def start
    @sentence = Answer.choice_sentence
  end

  def mark
    @user_answer = params[:answer]
    @sentence = Sentence.find(params[:id])
    correct_answer = @sentence.english
    @result = Answer.mark(user_answer: @user_answer,
      correct_answer: correct_answer)

    update_count(@sentence, @result)
    unless @sentence.save
      render text: 'save faild.'
    end

  end

  private

  def update_count(sentence, result)
    if sentence.count
      try = sentence.count.try
      correct = sentence.count.correct
    else
      try = 0
      correct = 0
    end

    try += 1
    correct += 1 if result

    sentence.count = Count.new(try: try, correct: correct)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sentences_controller.rb
class SentencesController < ApplicationController

  before_action :set_sentence, only: [:show, :edit, :update]

  def index
    @sentences = Sentence.all
  end

  def show
  end

  def edit
  end

  def update
    if @sentence.update(sentence_params)
      redirect_to @sentence, notice: 'Sentence was successfully updated.'
    else
      render action: 'edit'
    end
  end

  private

  def sentence_params
    params.require(:sentence).permit(:english, :japanese)
  end

  def set_sentence
    @sentence = Sentence.find(params[:id])
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sentences_helper.rb
module SentencesHelper
end

app/views/answers/start.html.erb
<%= form_tag mark_path, name: 'answer_form', remote: true do %>

  <div class="form-group">
    <%= label_tag "日本語: #{@sentence.japanese}" %>
  </div>

  <div class="form-group">
    <%= label_tag :answer, '回答' %>
    <%= text_field_tag :answer, '', size: 120,
      autocomplete: 'off', spellcheck: false,
      placeholder: 'Input the sentence in English',
      class: 'form-control' %>
    <%= hidden_field_tag :id, @sentence.id %>
  </div>

  <%= submit_tag '採点', class: 'btn btn-primary' %>

<% end %>

<div id="modal-result" class="panel">
  <p id="result-header" class="panel-heading"></p>
  <div class="panel-body">
    <p id="result-japanese"></p>
    <p id="result-english"></p>
    <p id="result-useranswer"></p>
    <p>
      <a id="modal-close" class="btn btn-danger">Close</a>
      <%= link_to 'Edit', edit_sentence_path(@sentence), class: 'btn btn-default' %>
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voca</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<ul class="nav nav-tabs">
    <li role="presentation"><%= link_to 'List', root_path %></li>
    <li role="presentation"><%= link_to 'Start', start_path %></li>
</ul>
<div id='container'>
    <%= yield %>
</div>

</body>
</html>

app/views/sentences/_form.html.erb
<%= form_for(@sentence) do |f| %>

  <% if @sentence.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sentence.errors.count, "error") %> prohibited this sentence frombeing saved:</h2>

      <ul>
        <% @sentence.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :id %>:
    <%= @sentence.id %>
  </div>
  <div class="form-group">
    <%= f.label :english %><br>
    <%= f.text_field :english, size: 80, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :japanese %><br>
    <%= f.text_field :japanese, size: 80, class: 'form-control' %>
  </div>
  <div class="actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>

<% end %>

app/views/sentences/edit.html.erb
<h1>Editing sentence</h1>

<%= render 'form' %>

<%= link_to 'Back', @sentence, class: 'btn btn-default' %>

app/views/sentences/index.html.erb
<h1>センテンス一覧</h1>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>No.</th>
      <th>原文</th>
      <th>訳文</th>
      <th>全</th>
      <th>正</th>
      <th>last</th>
    </tr>
  </thead>
  <tbody>
    <% @sentences.each do |sentence| %>
      <tr class="<%= cycle('odd-row', 'even-row') %>">
        <td><%= link_to sentence.id, sentence_path(sentence) %></td>
        <td><%= sentence.english %></td>
        <td><%= sentence.japanese %></td>
        <% count = sentence.count
           count ||= Count.new %>
        <td><%= count.try %></td>
        <td><%= count.correct %></td>
        <td><%= count.updated_at ?
                  count.updated_at.strftime('%Y/%m/%d-%H:%M:%S') :
                  '-' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<p id="page-top"><a href="#wrap">PAGE TOP</a></p>

app/views/sentences/show.html.erb
<% if notice %>
  <p id="notice" class="alert alert-success"><%= notice %></p>
<% end %>

<p>
  <strong>Id:</strong>
  <%= @sentence.id %>
</p>

<p>
  <strong>English:</strong>
  <%= @sentence.english %>
</p>

<p>
  <strong>Japanese:</strong>
  <%= @sentence.japanese %>
</p>

<%= link_to 'Edit', edit_sentence_path, class: 'btn btn-warning' %>